### ISSUE TITLE
bomb list

### ISSUE THREAD

**Issue by rbietin** [kramar42/kp-telegram-bot#6]
Output the current list of bombs, owners (_not as a  mention_), lists of users who where blown on those bombs (_not as a  mention_) and an expiration timer.

**Comment by 1over** [comment]
1. Bomb list is a kind of a cheat, you don't have to follow the chat, just type bomblist and immediately you know what words you have to skip.
2. Owners - good idea.
3. List of users - sounds also good.
4. Expiration timers - also good.

So, I would do it as a 'bombinfo' command

**Comment by rbietin** [comment]
> Bomb list is a kind of a cheat, you don't have to follow the chat, just type bomblist and immediately you know what words you have to skip.

Well, you can get it if you just use telegram search "/bomb " so I think it is fine to have this command.
